### PR TITLE
EmoteTome Release v1.0.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Kiroho

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Emote Tome added.<br>Provides a graphical interface for ingame emotes divided into three categories; core emotes, unlockable emotes and PvP rank emotes. <br><br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Emote Tome added.<br>Provides a graphical interface for ingame emotes divided into three categories; core emotes, unlockable emotes and PvP rank emotes. <br><br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Emote Tome added.<br>Provides a graphical interface for ingame emotes divided into three categories; core emotes, unlockable emotes and PvP rank emotes. <br><br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Emote Tome added.<br>Provides a graphical interface for ingame emotes divided into three categories; core emotes, unlockable emotes and PvP rank emotes. <br><br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Kiroho.<br><br>
Emote Tome added.<br>Provides a graphical interface for ingame emotes divided into three categories; core emotes, unlockable emotes and PvP rank emotes. <br><br><br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
