### PR TITLE
Farming Tracker Release v0.6.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Ecksofa

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires
Blish HUD 1.1.1 from [https://blishhud.com/](https://blishhud.com/)
and "Preview Releases" enabled in Blish Overlay
Settings.
<br>

**
New**<br>

- tracker
window can be resized. Not all UI elements will be responsive to the resizing.
Some will be cut off when window width is too small (e.g. filter/sort tab).<br>

- items
can be ignored. Ignored items are hideen in the summary tab and do not
contribute to profit calculations.<br>

-
automatic reset setting: reset on module startup (old behavior), never reset
(new behavior, manual reset required). In the future further automatic reset
options like in session tracker module might be implemented.<br>

- add
icon to buttons that open url in browser.<br>

- add drf
live tracker button to summary tab.<br>

- add
help to summary tab.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires
Blish HUD 1.1.1 from [https://blishhud.com/](https://blishhud.com/)
and "Preview Releases" enabled in Blish Overlay
Settings.
<br>

**
New**<br>

- tracker
window can be resized. Not all UI elements will be responsive to the resizing.
Some will be cut off when window width is too small (e.g. filter/sort tab).<br>

- items
can be ignored. Ignored items are hideen in the summary tab and do not
contribute to profit calculations.<br>

-
automatic reset setting: reset on module startup (old behavior), never reset
(new behavior, manual reset required). In the future further automatic reset
options like in session tracker module might be implemented.<br>

- add
icon to buttons that open url in browser.<br>

- add drf
live tracker button to summary tab.<br>

- add
help to summary tab.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires Blish HUD 1.1.1 from https://blishhud.com/ and "Preview Releases" enabled in Blish Overlay Settings.<br>

**New**<br>

- tracker window can be resized. Not all UI elements will be responsive to the resizing.<br>

Some will be cut off when window width is too small (e.g. filter/sort tab).<br>

- items can be ignored. Ignored items are hideen in the summary tab and do not<br>

contribute to profit calculations.<br>

- automatic reset setting: reset on module startup (old behavior), never reset<br>

(new behavior, manual reset required). In the future further automatic reset<br>

options like in session tracker module might be implemented.<br>

- add icon to buttons that open url in browser.<br>

- add drf live tracker button to summary tab.<br>

- add help to summary tab.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires Blish HUD 1.1.1 from https://blishhud.com/ and "Preview Releases" enabled in Blish Overlay Settings.<br>

**New**<br>

- tracker window can be resized. Not all UI elements will be responsive to the resizing.<br>

Some will be cut off when window width is too small (e.g. filter/sort tab).<br>

- items can be ignored. Ignored items are hideen in the summary tab and do not<br>

contribute to profit calculations.<br>

- automatic reset setting: reset on module startup (old behavior), never reset<br>

(new behavior, manual reset required). In the future further automatic reset<br>

options like in session tracker module might be implemented.<br>

- add icon to buttons that open url in browser.<br>

- add drf live tracker button to summary tab.<br>

- add help to summary tab.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Ecksofa.<br><br>
Requires Blish HUD 1.1.1 from https://blishhud.com/ and "Preview Releases" enabled in Blish Overlay Settings.<br>

**New**<br>

- tracker window can be resized. Not all UI elements will be responsive to the resizing. Some will be cut off when window width is too small (e.g. filter/sort tab).<br>

- items can be ignored. Ignored items are hideen in the summary tab and do not contribute to profit calculations.<br>

- automatic reset setting: reset on module startup (old behavior), never reset (new behavior, manual reset required). In the future further automatic reset options like in session tracker module might be implemented.<br>

- add icon to buttons that open url in browser.<br>

- add drf live tracker button to summary tab.<br>

- add help to summary tab.<br>

**Review by dlamkins — APPROVED** [review]

**Pull request merged**
