### PR TITLE
Legendary Armory Release v0.3.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Joe

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Joe.<br><br>
**Added** Lore View for unlocked Legendaries<br>**Improved** updating of Tooltips to reduce memory leak<br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Joe.<br><br>
**Added** Lore View for unlocked Legendaries<br>**Added **new Generation Section for Klobjarne Geirr<br>**Improved** updating of Tooltips to reduce memory leak<br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Joe.<br><br>
**Added** Lore View for unlocked Legendaries<br>**Added** new Generation Section for Klobjarne Geirr<br>**Improved** updating of Tooltips to reduce memory leak<br><br>

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Joe.<br><br>
**Added** Lore View for unlocked Legendaries<br>

<br>**Added** new Generation Section for Klobjarne Geirr<br>

<br>**Improved** updating of Tooltips to reduce memory leak<br><br>

**Comment by BlishHUD** [comment]
Release notes updated by Joe.<br><br>
**Added** Lore View for unlocked Legendaries<br>

<br>**Added** new Generation Section for Klobjarne Geirr<br>

<br>**Improved** updating of Tooltips to reduce memory leak<br><br>

**Pull request merged**
