### PR TITLE
Bomb your feet Release v0.0.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Soeed

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Soeed.<br><br>
**New Module!**<br>

Add a keybind to assist in placing ground target AoE skills at your feet. (PvE only)<br>

**ActionCam support**<br>

Temporarily disable action cam while holding your self-target keybind<br>

**Comment by dlamkins** [comment]
Seems there is an issue with the manifest. Nothing was generated. Check the generated bhm to see if there is something wrong with it.

**Review by dlamkins — CHANGES_REQUESTED** [review]
No content.

**Comment by a727891** [comment]
I'm not sure what you mean. When I download the SSRD build BHM from https://github.com/blish-hud/bhud-modules/releases/download/soeed.targetyourfeet_v0.0.1/Soeed.TargetYourFeet-0.0.1.bhm , I see a manifest.json inside the archive
@dlamkins

**Comment by a727891** [comment]
OH, the PR has no changes.

**Comment by BlishHUD** [comment]
Release deleted by Soeed.  PR will be closed.

**Pull request closed without merging**
