### PR TITLE
Mystic Crafting Release v1.1.0

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Atzie

### CODE REVIEW

**Comment by BlishHUD** [comment]
Release notes updated by Atzie.<br><br>
Stability updates&nbsp;<br>

- Fixes issue with items loading forever

- Fixes issue with UI freezing

- Added Trading Post option to Amalgamated Gemstones

- Fixes issue with linked items counting

- Improves object disposal (memory usage)

**Comment by ynzenu** [comment]
This can't be promoted to a public release right? No worries, I can bump the version once I've tested this prerelease.

**Comment by dlamkins** [comment]
@ynzenu that's correct.  Not supported yet.  Soon™️, though. 🤞

**Comment by ynzenu** [comment]
Ok, all good to go ahead with this one

**Comment by BlishHUD** [comment]
Release deleted by Atzie.  PR will be closed.

**Pull request closed without merging**
