### PR TITLE
Pathing Release v1.6.1

### PR DESCRIPTION
**Pull request by BlishHUD**
SSRD Build Triggered by Freesnöw

### CODE REVIEW

**Review by dlamkins — APPROVED** [review]

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**New** `occlude` attribute which allows markers to occlude other 3D Blish HUD elements (even without a texture).<br><br>

**Fixed**&nbsp;marker packs not reloading after updating or getting deleted.<br>

*Also* minor cleanup/improvements.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**New** `occlude` attribute which allows markers to occlude other 3D Blish HUD elements (even without a texture).<br><br>

**Fixed**&nbsp;marker packs not reloading after updating or getting deleted.<br>

*Also*&nbsp;minor cleanup/improvements.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**New** `occlude` attribute which allows markers to occlude other 3D Blish HUD elements (even without a texture).<br><br>

**Fixed**&nbsp;marker packs not reloading after updating or getting deleted.<br>

*Also*&nbsp;minor cleanup/improvements.<br><br>

**Known Issues:**<br>- The Pathing icon has mistakenly changed its order.&nbsp; This will be corrected in the next release.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**New** `occlude` attribute which allows markers to occlude other 3D Blish HUD elements (even without a texture).<br><br>

**Fixed**&nbsp;marker packs not reloading after updating or getting deleted.<br>

*Also*&nbsp;minor cleanup/improvements.<br><br>

**Known Issues:**<br>

****- The Pathing icon has mistakenly changed its order.&nbsp; This will be corrected in the next release.<br>

**Comment by BlishHUD** [comment]
Release notes updated by Freesnöw.<br><br>
**New** `occlude` attribute which allows markers to occlude other 3D Blish HUD elements (even without a texture).<br><br>

**Fixed**&nbsp;marker packs not reloading after updating or getting deleted.<br>

*Also*&nbsp;minor cleanup/improvements.<br><br>

**Known Issues:**<br>

****The Pathing icon has mistakenly changed its order.&nbsp; This will be corrected in the next release.<br>

**Pull request merged**
